# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: 赵虎阳的个人主页
url: http://gracefully.github.io
feed: /atom.xml
author_info: <a href="http://gracefully.github.io/">gracefully</a>

myblog:
  gavatar: images/2.jpg
  gpname: 赵虎阳
  linkedin: http://www.linkedin.com/in/gracefully
  github: https://github.com/gracefully
  email: mailto:zhaowuyang20008@163.com
  coverimgs: ["https://gracefully.github.io/images/cover_9.jpg"]
  postbgimg: []

categories: [python, books, php]
